### ISSUE TITLE
Missing pygments for CI + Qt build

### ISSUE THREAD

**Issue by kitchoi** [enthought/graphcanvas#24]
`pyface.api` + Qt requires `pygments` in the environment.

Currently the CI build for Qt fails because the environment does not have pygments.
https://travis-ci.com/github/enthought/graphcanvas/jobs/430207237

log file: 
[graphcanvas-pygments.log](https://github.com/enthought/graphcanvas/files/5510830/graphcanvas-pygments.log)

Alternatively, pygments could be made an optional dependency of pyface, see https://github.com/enthought/pyface/issues/655

**Comment by mdickinson** [comment]
This looks as though it's out of date (though I'm not sure exactly how and when it was fixed).

**Comment by mdickinson** [comment]
It was fixed in this commit: https://github.com/enthought/graphcanvas/commit/1fcc3e93cd70ee90fbf608941e8546aaf8108bb5

**Comment by mdickinson** [comment]
> It was fixed in this commit: 1fcc3e9

Hmm, no; that commit didn't go into the master branch. In any case, it no longer appears to be a problem on the master branch.
