### ISSUE TITLE
Is distribute still a dependency of graphcanvas?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/graphcanvas#27]
The README lists `distribute` as a dependency but i don't see any users in the codebase.

**Comment by mdickinson** [comment]
That reference goes back 10 years. We should just delete it. There's no runtime dependence on either `distribute` or `setuptools`.

**Comment by mdickinson** [comment]
FTR, the `distribute` reference was introduced here: https://github.com/enthought/graphcanvas/commit/b4622b9c338c7b07fec9cb22300c22f680464aec
