### ISSUE TITLE
Cron Job Test Failure

### ISSUE THREAD

**Issue by aaronayres35** [enthought/graphcanvas#29]
The cron job has recently failed on the test `graphcanvas.tests.test_graph_container.TestGraphContainer.test_do_layout`.  see: https://travis-ci.com/github/enthought/graphcanvas/builds/227898846

Given the timing of the failure, and the only difference in installed packages between the cron job passing and failing was `enable 5.1.0` to `enable 5.1.1` I suspect this PR is relevant https://github.com/enthought/enable/pull/820

**Comment by aaronayres35** [comment]
The latest cron job run passed.  I am not sure what changed to fix the test failure, but in any case I am going to close this issue as it appears to be resolved.
ref: https://travis-ci.com/github/enthought/graphcanvas/builds/228633087

**Comment by mdickinson** [comment]
I think this is an intermittent failure, possibly based on use of a random seed somewhere. I've opened #32.
